tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/core"

# tools
brew "git"
brew "tree"
brew "curl"
brew "wget"
brew "lazygit"

# nvim
brew "neovim"
brew "ripgrep"
brew "fd"
brew "tree-sitter"
brew "node"

# coding
brew "python3"
brew "ruby"
#brew "composer"
#brew "php"

# fun
#brew "cmatrix"
#brew "tty-clock"

# casks
cask "font-meslo-lg-nerd-font"
#cask "font-hack-nerd-font"
cask "kitty"
cask "docker"

# nice to have
cask "fliqlo"
#cask "stats"
#cask "itsycal"
#cask "iterm2"
