return {
  -- {
  --   -- This plugin adds a Treesitter configuration and abstraction layer to Neovim.
  --   -- Link: https://github.com/nvim-treesitter/nvim-treesitter
  --
  --   'nvim-treesitter/nvim-treesitter',
  --   branch = 'master',
  --   build = ':TSUpdate',
  --   opts = {
  --     -- Parsers to install
  --     ensure_installed = {
  --       'bash',
  --       'c',
  --       'css',
  --       'dockerfile',
  --       'gitignore',
  --       'html',
  --       'htmldjango',
  --       'java',
  --       'javascript',
  --       'json',
  --       'lua',
  --       'luadoc',
  --       'make',
  --       'markdown',
  --       'markdown_inline',
  --       'php',
  --       'phpdoc',
  --       'python',
  --       'regex',
  --       'toml',
  --       'tsx',
  --       'vim',
  --       'vimdoc',
  --       'vue',
  --       'yaml',
  --       --'help',
  --       --'swift',
  --     },
  --     sync_install = false,
  --     auto_install = true,
  --
  --     -- Highlight
  --     highlight = {
  --       enable = true,
  --       disable = {},
  --     },
  --
  --     -- Incremental selection
  --     incremental_selection = {
  --       enable = true,
  --       keymaps = {
  --         init_selection = '<CR>',
  --         node_incremental = '<CR>',
  --         scope_incremental = false,
  --         node_decremental = '<BS>',
  --       },
  --     },
  --
  --     -- Indention
  --     indent = {
  --       enable = true,
  --     },
  --   },
  --   config = function(_, opts)
  --     require('nvim-treesitter.configs').setup(opts)
  --
  --     local parser_config = require('nvim-treesitter.parsers').get_parser_configs()
  --
  --     -- tsx: Update filetypes
  --     parser_config.tsx.filetype_to_parsername = { 'javascript', 'typescript.tsx' }
  --
  --     -- asciidoc: Adds a (experimental) parser for AsciiDoc.
  --     -- Source: https://github.com/nvim-treesitter/nvim-treesitter?tab=readme-ov-file#adding-parsers
  --     -- `:TSInstallFromGrammar asciidoc`
  --     -- local parser_config = require('nvim-treesitter.parsers').get_parser_configs()
  --     parser_config.asciidoc = {
  --       install_info = {
  --         -- url = 'https://github.com/tigion/tree-sitter-asciidoc', -- local path or git repo
  --         url = '/Users/christoph/projects/neovim/tree-sitter-asciidoc',
  --         files = { 'src/parser.c' },
  --         branch = 'main',
  --       },
  --     }
  --   end,
  -- },

  -- {
  --   -- This plugin adds syntax aware text-objects to Neovim.
  --   -- Link: https://github.com/nvim-treesitter/nvim-treesitter-textobjects
  --
  --   'nvim-treesitter/nvim-treesitter-textobjects',
  -- },
}
